name: 'Build Datavarasto: File Service'
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Retag previous images
      shell: bash
      run: >-
        TAG=${{ github.event.inputs.env }}
        TAG_PREVIOUS=${TAG}_previous

        if [ "docker image inspect fs-1:${TAG}" > /dev/null ];
        then
          docker tag fs-1:${TAG} fs-1:${TAG_PREVIOUS}
        fi

    - name: Build images
      shell: bash
      run: |
        cd ~/repositories/file-service
        docker build -t fs-1:${{ github.event.inputs.env }} .
