name: Build Sports Location Tracker
inputs:
  env:
    required: true
  google-maps-api-key:
    required: true
  postgres-password:
    required: true

runs:
  using: composite
  steps:
    - name: Build images
      shell: bash
      run: |
        cd ~/repositories/Sports-Location-Tracker-Public
        docker build -t slt_webapp:latest -f .dockerfiles/webapp.Dockerfile .
        docker build -t slt_server:latest --build-arg NODE_ENV=production -f .dockerfiles/server.Dockerfile .
        docker build -t slt_db:latest -f .dockerfiles/db.Dockerfile .
    - name: Build containers
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/docker/sports-location-tracker
        TAG="latest" docker-compose \
          -f docker-compose.${{ github.event.inputs.env }}.yml \
          build \
          --build-arg GOOGLE_MAP_API_KEY=${{ github.event.inputs.google-maps-api-key }} \
          --build-arg POSTGRES_USER=admin \
          --build-arg POSTGRES_PASSWORD=${{ github.event.inputs.postgres-password }}
