name: Build Sports Location Tracker
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Build images
      shell: bash
      run: |
        cd ~/repositories/Sports-Location-Tracker-Public
        docker build -t slt_webapp:latest -f .dockerfiles/webapp.Dockerfile .
        docker build -t slt_server:latest --build-arg NODE_ENV=production -f .dockerfiles/server.Dockerfile .
        docker build -t slt_db:latest -f .dockerfiles/db.Dockerfile .
    - name: Build containers
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/docker/sports-location-tracker
        TAG="latest" docker-compose \
          --file docker-compose.${{ github.event.inputs.env }}.yml \
          --env-file ~/secrets/sports-location-tracker-${{ github.event.inputs.env }}.env \
          build
