name: Build Sports Location Tracker
inputs:
  branch:
    required: true
  env:
    required: true
  google-maps-api-key:
    required: true
  postgres-password:
    required: true

runs:
  using: composite
  steps:
    - name: Build images
      shell: bash
      run: |
        cd ~/repositories/Sports-Location-Tracker-Public/.dockerfiles
        docker build -t slt_webapp:latest webapp.Dockerfile
        docker build -t slt_server:latest --build-arg NODE_ENV=production server.Dockerfile
        docker build -t slt_db:latest db.Dockerfile
    - name: Build containers
      shell: bash
      run: |
        cd ~/repositories/Innovaatioprojekti-CI-CD/docker/sports-location-tracker/docker-compose.yml
        TAG="latest" docker-compose build \
          --build-arg GOOGLE_MAP_API_KEY=${{ github.event.inputs.google-maps-api-key }} \
          --build-arg POSTGRES_USER=admin \
          --build-arg POSTGRES_PASSWORD=${{ github.event.inputs.postgres-password }}
