name: 'Build Datavarasto: UI'
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Retag previous images
      shell: bash
      run: >-
        TAG=${{ inputs.env }}
        TAG_PREVIOUS=${TAG}_previous

        if (docker image inspect ui-1:${TAG} > /dev/null);
        then
          docker tag ui-1:${TAG} ui-1:${TAG_PREVIOUS}
        fi

    - name: Build images
      shell: bash
      run: |
        cd ~/repositories/datavarasto-ui
        docker build -t ui-1:${{ inputs.env }} .
