name: 'Build Datavarasto: Gateway'
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Retag previous images
      shell: bash
      run: >-
        TAG=${{ inputs.env }}
        TAG_PREVIOUS=${TAG}_previous

        if (docker image inspect gw-1:${TAG} > /dev/null);
        then
          docker tag gw-1:${TAG} gw-1:${TAG_PREVIOUS}
        fi

    - name: Build images
      shell: bash
      run: |
        cd ~/repositories/gateway
        docker build -t gw-1:${{ inputs.env }} .
