name: Rollback Sports Location Tracker
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Retag images
      shell: bash
      run: |
        docker tag slt_webapp:${{ github.event.inputs.env }}_previous slt_webapp:${{ github.event.inputs.env }}
        docker tag slt_server:${{ github.event.inputs.env }}_previous slt_server:${{ github.event.inputs.env }}
        docker tag slt_db:${{ github.event.inputs.env }}_previous slt_db:${{ github.event.inputs.env }}
