name: Rollback Sports Location Tracker
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Retag images
      shell: bash
      run: >-
        TAG=${{ inputs.env }}
        TAG_PREVIOUS=${TAG}_previous
        TAG_TMP=${TAG}_tmp

        if (docker image inspect slt_webapp:${TAG_PREVIOUS} > /dev/null \
          && docker image inspect slt_server:${TAG_PREVIOUS} > /dev/null \
          && docker image inspect slt_db:${TAG_PREVIOUS} > /dev/null \
          && docker image inspect slt_webapp:${TAG} > /dev/null \
          && docker image inspect slt_server:${TAG} > /dev/null \
          && docker image inspect slt_db:${TAG} > /dev/null);
        then
          docker tag slt_webapp:${TAG} slt_webapp:${TAG_TMP}
          docker tag slt_server:${TAG} slt_server:${TAG_TMP}
          docker tag slt_db:${TAG} slt_db:${TAG_TMP}

          docker tag slt_webapp:${TAG_PREVIOUS} slt_webapp:${TAG}
          docker tag slt_server:${TAG_PREVIOUS} slt_server:${TAG}
          docker tag slt_db:${TAG_PREVIOUS} slt_db:${TAG}

          docker tag slt_webapp:${TAG_TMP} slt_webapp:${TAG_PREVIOUS}
          docker tag slt_server:${TAG_TMP} slt_server:${TAG_PREVIOUS}
          docker tag slt_db:${TAG_TMP} slt_db:${TAG_PREVIOUS}

          docker image rm slt_webapp:${TAG_TMP}
          docker image rm slt_server:${TAG_TMP}
          docker image rm slt_db:${TAG_TMP}
        else
          exit 1
        fi
