version: '3'

services:
  webapp:
    hostname: slt_webapp_stg
    restart: always
    image: slt_webapp:${TAG}
    ports:
      - '81:81'
    environment:
      BASEPATH: ${BASEPATH}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    depends_on:
      - server
    networks:
      - stg

  server:
    hostname: node_server
    restart: always
    image: slt_server:${TAG}
    environment:
      BASEPATH: ${BASEPATH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '9000:9000'
    depends_on:
      - postgres
    networks:
      - stg

  postgres:
    restart: always
    image: slt_db:${TAG}
    environment:
      POSTGRES_DB: sports_location_tracker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - stg
    ports:
      - '5432:5432'
    volumes:
      - ~/volumes/sports-location-tracker/stg/db-data:/var/lib/postgresql/data

networks:
  stg:
