version: '3'

services:
  webapp:
    hostname: slt_webapp_prd
    restart: always
    image: slt_webapp:${TAG}
    ports:
      - '81'
    environment:
      BASEPATH: ${BASEPATH}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    depends_on:
      - server
      - adminer
    networks:
      - prd

  server:
    hostname: node_server
    restart: always
    image: slt_server:${TAG}
    environment:
      BASEPATH: ${BASEPATH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '9000'
    depends_on:
      - postgres
    networks:
      - prd

  postgres:
    restart: always
    image: slt_db:${TAG}
    environment:
      POSTGRES_DB: sports_location_tracker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - prd
    ports:
      - '5432'
    volumes:
      - ~/volumes/sports-location-tracker/prd/db-data:/var/lib/postgresql/data

  adminer:
    hostname: adminer
    image: adminer:4.7.7
    restart: always
    ports:
      - '1081:8080'
    depends_on:
      - postgres
    networks:
      - prd

networks:
  prd:
