name: Deploy Sports Location Tracker
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Build and start containers
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/docker/sports-location-tracker
        TAG=${{ inputs.env }} docker-compose \
          --file docker-compose.${{ inputs.env }}.yml \
          --env-file ~/secrets/sports-location-tracker-${{ inputs.env }}.env \
          up -d
