name: Deploy Sports Location Tracker
inputs:
  env:
    required: true

runs:
  using: composite
  defaults:
    run:
      shell: bash
  steps:
    - name: Build and start containers
      run: |
        cd $GITHUB_WORKSPACE/docker/sports-location-tracker
        TAG=${{ github.event.inputs.env }} docker-compose \
          --file docker-compose.${{ github.event.inputs.env }}.yml \
          --env-file ~/secrets/sports-location-tracker-${{ github.event.inputs.env }}.env \
          up -d
