name: Deploy Datavarasto
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Build and start containers
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/docker/datavarasto
        TAG=${{ github.event.inputs.env }} docker-compose \
          --file docker-compose.${{ github.event.inputs.env }}.yml \
          --env-file ~/secrets/datavarasto-${{ github.event.inputs.env }}.env \
          up -d
