name: Test Datavarasto
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Move to repository
      run: cd ~/repositories/datavarasto-ui

    - name: Run e2e tests
      uses: cypress-io/github-action@v2
        with:
          browser: chrome
