name: Test Datavarasto
inputs:
  env:
    required: true

runs:
  using: composite
  steps:
    - name: Run e2e tests
      shell: bash
      uses: cypress-io/github-action@v2
      with:
        project: ~/repositories/datavarasto-ui
        browser: chrome
