version: '3'

services:
  ui-stg:
    depends_on:
      - database-stg
      - user-management-service-stg
      - gateway-stg
      - file-service-stg
    hostname: ui-1_stg
    container_name: ui-1_stg
    image: ui-1:${TAG}
    restart: always
    ports:
      - '4200:4200'
    networks:
      - stg

  gateway-stg:
    depends_on:
      - database-stg
      - user-management-service-stg
    image: gw-1:${TAG}
    hostname: gateway
    container_name: gateway_stg
    restart: always
    ports:
      - '3000:3000'
    networks:
      - stg

  user-management-service-stg:
    depends_on:
      - database-stg
    image: ums-1:${TAG}
    hostname: user_management_service
    container_name: user_management_service_stg
    restart: always
    ports:
      - '3001:3001'
    networks:
      - stg

  file-service-stg:
    depends_on:
      - database-stg
      - user-management-service-stg
    image: fs-1:${TAG}
    hostname: file_service
    container_name: file_service_stg
    restart: always
    ports:
      - '3002:3002'
    networks:
      - stg

  database-stg:
    image: mongo-db:${TAG}
    hostname: mongo-db
    container_name: mongo-db_stg
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dataStorage
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/volumes/datavarasto/stg/db-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - stg

networks:
  stg:
