version: '3'

services:
  ui:
    depends_on:
      - database
      - user-management-service
      - gateway
      - file-service
    hostname: ui-1_prd
    container_name: ui-1_prd
    image: ui-1:${TAG}
    restart: always
    ports:
      - '4200'
    networks:
      - prd

  gateway:
    depends_on:
      - database
      - user-management-service
    image: gw-1:${TAG}
    hostname: gateway
    container_name: gateway_prd
    restart: always
    ports:
      - '3000'
    networks:
      - prd

  user-management-service:
    depends_on:
      - database
    image: ums-1:${TAG}
    hostname: user_management_service
    container_name: user_management_service_prd
    restart: always
    ports:
      - '3001'
    networks:
      - prd

  file-service:
    depends_on:
      - database
      - user-management-service
    image: fs-1:${TAG}
    hostname: file_service
    container_name: file_service_prd
    restart: always
    ports:
      - '3002'
    networks:
      - prd

  database:
    image: mongo-db:${TAG}
    hostname: mongo-db
    container_name: mongo-db_prd
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dataStorage
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/volumes/datavarasto/prd/db-data:/data/db
    ports:
      - '27017'
    networks:
      - prd

networks:
  prd:
