services:
  ui:
    hostname: ui-1_stg
    image: ui-1:${TAG}
    restart: always
    ports:
      - '4200:4200'
    networks:
      - stg

  gateway:
    image: gw-1:${TAG}
    restart: always
    ports:
      - '3000:3000'
    networks:
      - stg

  user-management-service:
    image: ums-1:${TAG}
    restart: always
    ports:
      - '3001:3001'

  file-service:
    image: fs-1:${TAG}
    restart: always
    ports:
      - '3002:3002'
    networks:
      - stg

  database:
    image: 'mongo'
    restart: always
    container_name: 'mongo-db'
    environment:
      - MONGO_INITDB_DATABASE=dataStorage
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - stg

networks:
  stg:
