name: Deploy App
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy'
        required: true
        type: choice
        options: [sports-location-tracker]
      branch:
        description: 'Branch to deploy'
        required: true
        default: main
      env:
        description: 'Deploy environment'
        required: true
        type: choice
        options: [stg, prd]
        default: stg

jobs:
  fetch-repo:
    runs-on: self-hosted
    steps:
      - name: Get repo name
        id: repo
        run: >-
          case ${{ github.event.inputs.app }} in
            sports-location-tracker) 
              echo '::set-output name=SSH_HOSTNAME::github.com-repo-sports-location-tracker'
              echo '::set-output name=GITHUB_ACCOUNT::ninopenttinen'
              echo '::set-output name=REPO_NAME::Sports-Location-Tracker-Public';;
            *) 
              echo "Invalid input"
              exit 1;;
          esac
      - name: Pull from repo
        run: |
          cd ~/repositories/${{ steps.repo.outputs.REPO_NAME }}
          git pull origin ${{ github.event.inputs.branch }}
      - name: Clone from repo if pull fails
        if: ${{ failure() }}
        run: |
          cd ~/repositories
          git clone git@${{ steps.repo.outputs.SSH_HOSTNAME }}:${{ steps.repo.outputs.GITHUB_ACCOUNT }}/${{ steps.repo.outputs.REPO_NAME }}.git
      - name: Checkout to selected branch
        if: ${{ always() }}
        run: |
          cd ~/repositories/${{ steps.repo.outputs.REPO_NAME }}
          git checkout ${{ github.event.inputs.branch }}

  build:
    needs: fetch-repo
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Run build action for ${{ github.event.inputs.app }}
        uses: ./build-actions/${{ github.event.inputs.app }}
        with:
          env: ${{ github.event.inputs.env }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Run deploy action for ${{ github.event.inputs.app }}
        uses: ./deploy-actions/${{ github.event.inputs.app }}
        with:
          env: ${{ github.event.inputs.env }}
