name: Deploy App
on:
  workflow_dispatch:
    inputs:
      app:
        description: "App to deploy"
        required: true
        type: choice
        options: [test_app]
      branch:
        description: "Branch to deploy"
        required: true
        default: main
      env:
        description: "Deploy environment"
        required: true
        type: choice
        options: [stg, prd]
        default: stg

jobs:
  fetch-repo:
    runs-on: self-hosted
    steps:
      - name: Get repo name
        id: repo
        run: >-
          case ${{ github.event.inputs.app }} in
            test_app) 
              echo '::set-output FAKE_SSH_HOSTNAME::github.com-repo-sports-location-tracker'
              echo '::set-output GITHUB_ACCOUNT::ninopenttinen'
              echo '::set-output NAME::Sports-Location-Tracker-Public';;
            *) 
              echo "Invalid input"
              exit 1;;
          esac
      - name: Pull from repo
        run: |
          cd ~/repositories/${{ steps.repo.outputs.NAME }}
          git pull origin ${{ github.events.inputs.branch }}
      - name: Clone from repo if pull fails
        if: ${{ failure() }}
        run: |
          cd ~/repositories
          git clone git@${{ steps.repo.outputs.FAKE_SSH_HOSTNAME }}:${{ steps.repo.outputs.GITHUB_ACCOUNT }}/${{ steps.repo.outputs.NAME }}.git
          cd ${{ steps.repo.outputs.NAME }}
      - name: Checkout to selected branch
        run: git checkout ${{ github.events.inputs.branch }}
