name: Deploy App
on:
  workflow_dispatch:
    inputs:
      app:
        description: "Choose app to deploy"
        required: true
        type: choice
        options: [test_app]
      branch:
        required: true
        default: main
      env:
        description: "Choose deploy environment"
        required: true
        type: choice
        options: [stg, prd]
        default: stg

jobs:
  fetch-repo:
    runs-on: self-hosted
    steps:
      - name: Get repo name
        id: repo_name
        run: >-
          case ${{ github.event.inputs.app }} in
            test_app) echo "::set-output name=Sports-Location-Tracker-Public";;
            *) exit 1;;
          esac
      - name: Pull from repo
        run: |
          cd ~/repositories/${{ steps.repo_name.outputs.name }}
          git pull origin ${{ github.events.inputs.branch }}
      - name: Clone from repo if pull fails
        if: ${{ failure() }}
        run: |
          cd ~/repositories
          git clone git@github.com:ninopenttinen/${{ steps.repo_name.outputs.name }}.git
          cd ${{ steps.repo_name.outputs.name }}
