name: E2E Test
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      env:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      app:
        description: 'App to test'
        required: true
        type: choice
        options: [datavarasto]
        default: datavarasto
      env:
        description: 'Environment'
        required: true
        type: choice
        options: [stg, prd]
        default: stg

jobs:
  e2e-test:
    runs-on: self-hosted
    steps:
      - name: Run e2e tests for ${{ github.event.inputs.app }}
        if: ${{ github.event.inputs.app }} == 'datavarasto'
        uses: cypress-io/github-action@v2
        with:
          working-directory: ~/repositories/datavarasto-ui
          headless: true
          wait-on: 'http://localhost:80/${{ github.event.inputs.env }}/${{ github.event.inputs.app }}'
