name: E2E Test
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      env:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      app:
        description: 'App to test'
        required: true
        type: choice
        options: [datavarasto]
        default: datavarasto
      env:
        description: 'Environment'
        required: true
        type: choice
        options: [stg, prd]
        default: stg

jobs:
  e2e-test:
    runs-on: self-hosted
    container:
      image: cypress/base:14
      env:
        CYPRESS_baseUrl: http://172.17.0.1:80
      ports:
        - 3333
      volumes:
        - /home/project/repositories/datavarasto-ui:/workdir
    steps:
      #- name: Verify install was successful
      #  run: npx cypress verify
      - name: Run E2E tests
        run: |
          cd /workdir
          ls -a
          npx cypress run
