name: E2E Test
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      app:
        description: 'App to test'
        required: true
        type: choice
        options: [datavarasto]
        default: datavarasto

jobs:
  e2e-test:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Run e2e tests for ${{ github.event.inputs.app }}
        uses: cypress-io/github-action@v2
        with:
          project: ~/repositories/datavarasto-ui
          browser: chrome
