name: Rollback
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App to rollback'
        required: true
        type: choice
        options: [sports-location-tracker]
      env:
        description: 'Target environment'
        required: true
        type: choice
        options: [stg, prd]
        default: stg

concurrency:
  group: deploy
  cancel-in-progress: false # put workflow in queue instead of canceling

jobs:
  rollback:
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        # "uses" Cannot be used dynamically via expression, so we have to make own step for each app with an "if" clause...
      - name: Run rollback action for ${{ github.event.inputs.app }}
        if: github.event.inputs.app == 'sports-location-tracker'
        uses: ./rollback-actions/sports-location-tracker
        with:
          env: ${{ github.event.inputs.env }}

  deploy:
    needs: rollback
    runs-on: self-hosted
    if: ${{ needs.rollback.result == 'success' }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Run deploy action for ${{ github.event.inputs.app }}
        if: github.event.inputs.app == 'sports-location-tracker'
        uses: ./deploy-actions/sports-location-tracker
        with:
          env: ${{ github.event.inputs.env }}
