name: Server connection test
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Runner echoes this message"
        required: true
        default: "Hello World"

jobs:
  test-connection:
    runs-on: self-hosted
    steps:
      - run: |
          ls -a
          cd
          ls -a
          echo ${{ github.event.inputs.message }}
