name: Update repo on server
on:
  push:
    branches:
      - main
    paths:
      - docker/**

jobs:
  update-repo:
    runs-on: self-hosted
    steps:
      - name: Pull repo from github
        run: |
          cd ~/Innovaatioprojekti-CI-CD
          git pull origin main
