name: Update CICD repo on server
on:
  push:
    branches:
      - main
    paths:
      - docker/**

jobs:
  update-repo:
    runs-on: self-hosted
    steps:
      - name: Pull repo from github
        run: |
          cd ~/repositories/Innovaatioprojekti-CI-CD
          git pull origin main
      - name: Clone from repo if pull fails
        if: ${{ failure() }}
        run: |
          cd ~/repositories
          git clone git@github.com-repo-cicd/5G00BD88-3006-Innovaatioprojekti/Innovaatioprojekti-CI-CD.git
